### ISSUE TITLE
Warning in the Hooks

### ISSUE THREAD

**Issue by acidjunk** [DavidODonovan/react-dims#2]
Nice stuff. Finally an easy way to do powerful stuff with dynamic dimensions => SVG/Canvas content. Very practical :)

One question though:

When I use it I get a warning in one of the two `useEffect()` hooks.
  
```
Compiled with warnings.

src/contexts/ReactDims.jsx
  dReact Hook useEffect has a missing dependency: 'getNodeDimensions'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

I used the code from the github repo. Is something wrong with it (it works just fine)?

**Comment by DavidODonovan** [comment]
yes I've recently noticed the same warning. I don't have time to look into it now ( in Australia preparing for more floods in the morning). However a quick fix is to pass getNodeDimensions to the useEffect hook as a callback, like so; 

  useEffect((getNodeDimensions)=>{
    window.addEventListener('resize', getNodeDimensions);
    return ()=>{ window.removeEventListener('resize', getNodeDimensions)};
  }, []);

That will leave you with a slightly less dramatic warning 😅.

There is a thread on stackoverflow here: 
https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook

I've just skimmed through it once but don't yet have a deep enough understanding of what's going. I'll have to return to it later. - as I said very busy this evening..
Let me know if you can make sense of it! 🤟

**Comment by acidjunk** [comment]
Thanks. Playing a bit with it. When I have some time I will try to make a PR.

**Comment by DavidODonovan** [comment]
Okay thanks. I'm working on something totally different right now so it will be while before I return to this. I think this module would work better as a hook anyway, eg; ` const dims = useDims()` 
So it might be time to make some breaking changes...

**Comment by DavidODonovan** [comment]
I had a couple of hours spare and rewrote ReactDims as a hook. It is _MUCH NICER_ to use, and the refactor does not trigger any warnings, so that's good as well.
See the example in the useReactDims directory.  I plan to test and then publish this soon. Add a pull request if you see a way to improve.
